### ISSUE TITLE
Conda package has broken libpoppler dependency

### ISSUE THREAD

**Issue by rmsare** [rmsare/scarplet#69]
**Describe the bug**

**To Reproduce**
`conda install -y scarplet -c conda-forge` in main environment or fresh virtual environment.

This leads to a failure to find libpoppler.so.76.

Full traceback:
```bash
(testenv) ~ » python3.7 -c "import scarplet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/site-packages/scarplet/__init__.py", line 1, in <module>
    from scarplet.core import *
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/site-packages/scarplet/core.py", line 18, in <module>
    from scarplet.dem import DEMGrid
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/site-packages/scarplet/dem.py", line 14, in <module>
    from osgeo import gdal, gdalconst
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rmsare/miniconda3/envs/test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory
```

**Expected behavior**
Successful installation

**Desktop (please complete the following information):**
 - Ubuntu 14/16 LTS
 - Python 3.7

**Comment by rmsare** [comment]
This seems to be resolved and may have been an upstream gdal or libpoppler issue. Installation now works in a fresh virtual environment.
